### ISSUE TITLE
Very basic documentation issues, and possibly a bug.

### ISSUE THREAD

**Issue by j3pic** [ruby-druid/ruby-druid#7]
Whoever wrote the README.md dropped this in the hallway:

    require 'druid'

EDIT: Also, the README.md has:

    client = Druid::Client.new('zk1:2181,zk2:2181/druid')
    query = Druid::Query.new('service/source')
    client.send(query)

But there's no `send` method in the `Druid::Client` class.
Also, the line defining `query` fails because of an `ArgumentError` (but that looks like an actual bug rather than a documentation issue):

    ArgumentError: When assigning attributes, you must pass a hash as an argument.
    from /Users/me/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activemodel-5.0.2/lib/active_model/attribute_assignment.rb:28:in `assign_attributes'

**Comment by itszootime** [comment]
The documentation has been updated in https://github.com/ruby-druid/ruby-druid/commit/3702e0a659ec725e573ecf3922ca3906178965f5, I'll close this issue.
