### ISSUE TITLE
What is the correct way to query?

### ISSUE THREAD

**Issue by aswani521** [ruby-druid/ruby-druid#8]
I followed the read me and I get this error:
2.2.0 :022 > dc = Druid::Client.new(uri).query('service/source')
NoMethodError: undefined method `query' for #<Druid::Client:0x007fcf1ebe7950>

which makes sense because there is no method query in: https://github.com/ruby-druid/ruby-druid/blob/master/lib/druid/client.rb

**Comment by itszootime** [comment]
Oops - the readme was quite out of date. I've updated it now, you should find everything you need there 🙂.
